# Generated by Django 4.2.4 on 2023-08-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_shopgoods_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopgoods",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
